---
modules-search: [ "/calamares/modules" ]

sequence:
  - show:
      - welcome
  - locale
  - keyboard
  - partition
  - users
  - displaymanager
  - packages
  - machineid
  - fstab
  - initramfs
  - bootloader
  - finished

branding: archinstaller
dont-chroot: false

