---
packages:
  remove: []
  install:
    - plasma-desktop
    - konsole
    - dolphin
    - kate
    - sddm
    - sddm-kcm
    - networkmanager
    - grub
    - efibootmgr
    - linux
    - linux-firmware
    - pamac-qt
    - pamac-flatpak-plugin
    - pamac-snap-plugin
