name: Build ArchInstaller ISO
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install archiso dependencies
        run: |
          sudo apt update
          sudo apt install -y archiso git wget xorriso squashfs-tools dosfstools
      - name: Build ISO
        run: |
          chmod +x build_iso.sh
          sudo ./build_iso.sh
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ArchInstaller_v0.0.7.iso
          path: out/*.iso
