name: Build ArchInstaller ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso git base-devel

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO
        run: |
          cd archiso
          mkdir -p ../out
          mkarchiso -v -w ./work -o ../out .

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArchInstaller-ISO
          path: out/*.iso
