name: Build ISO

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init pacman keys
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Download Chaotic-AUR keyring manually
        run: |
          curl -LO https://raw.githubusercontent.com/chaotic-aur/chaotic-keyring/master/chaotic.gpg
          curl -LO https://raw.githubusercontent.com/chaotic-aur/chaotic-keyring/master/chaotic-trusted

      - name: Install Chaotic-AUR keyring manually
        run: |
          install -Dm644 chaotic.gpg /usr/share/pacman/keyrings/chaotic.gpg
          install -Dm644 chaotic-trusted /usr/share/pacman/keyrings/chaotic-trusted

      - name: Add Chaotic-AUR repo
        run: |
          echo "" >> /etc/pacman.conf
          echo "[chaotic-aur]" >> /etc/pacman.conf
          echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf

      - name: Download mirrorlist manually
        run: |
          curl -Lo /etc/pacman.d/chaotic-mirrorlist \
            https://raw.githubusercontent.com/chaotic-aur/chaotic-mirrorlist/master/chaotic-mirrorlist

      - name: Update pacman
        run: pacman -Syy

      - name: Install archiso
        run: pacman -Sy --noconfirm archiso git

      - name: Fix line endings
        run: sed -i 's/\r$//' build_iso.sh

      - name: Build ISO
        run: bash ./build_iso.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-custom
          path: out/*.iso
