name: Build ArchInstaller ISO

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm archiso git sudo base-devel wget

      - name: Build ISO
        run: |
          chmod +x build_iso.sh
          ./build_iso.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArchInstaller_v0.0.5_EXTREME++
          path: out/*.iso